# Generated by Django 3.2.9 on 2021-12-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'Departamento Docente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NoDocentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'Departamento No Docente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.CharField(max_length=50, verbose_name='Edad')),
                ('oficina', models.CharField(choices=[('0', 'Limpieza'), ('1', 'Administrativo'), ('2', 'Tesorería'), ('3', 'Dirección')], max_length=50, verbose_name='Oficina')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.nodocentes')),
            ],
            options={
                'verbose_name': 'No Docente',
                'verbose_name_plural': 'No Docentes',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.CharField(max_length=50, verbose_name='Edad')),
                ('materia', models.CharField(choices=[('0', 'Programación 2'), ('1', 'Práctica 1'), ('2', 'Matemática Aplicada'), ('3', 'Modelado de Sistemas'), ('4', 'Sistemas Operativos'), ('5', 'Base de Datos')], max_length=50, verbose_name='Materia')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.docentes')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
