# Generated by Django 3.2.9 on 2021-12-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='area',
        ),
        migrations.RemoveField(
            model_name='nodocente',
            name='area',
        ),
        migrations.AlterField(
            model_name='nodocente',
            name='oficina',
            field=models.CharField(choices=[('0', 'Limpieza'), ('1', 'Administrativo'), ('2', 'Tesorería'), ('3', 'Dirección')], max_length=50, verbose_name='Área'),
        ),
        migrations.DeleteModel(
            name='Docentes',
        ),
        migrations.DeleteModel(
            name='NoDocentes',
        ),
    ]
