# Generated by Django 3.2.9 on 2021-12-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20211202_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('years', models.IntegerField(verbose_name='Edad')),
                ('job', models.CharField(choices=[('0', 'Docente'), ('1', 'No Docente')], max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personales',
            },
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='NoDocente',
        ),
    ]
