# Generated by Django 3.2.9 on 2021-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20211203_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.CharField(max_length=50, verbose_name='Edad')),
                ('materia', models.CharField(choices=[('0', 'Programación 2'), ('1', 'Práctica 1'), ('2', 'Matemática Aplicada'), ('3', 'Modelado de Sistemas'), ('4', 'Sistemas Operativos'), ('5', 'Base de Datos')], max_length=50, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.CharField(max_length=50, verbose_name='Edad')),
                ('oficina', models.CharField(choices=[('0', 'Limpieza'), ('1', 'Administrativo'), ('2', 'Tesorería'), ('3', 'Dirección')], max_length=50, verbose_name='Área')),
            ],
            options={
                'verbose_name': 'No Docente',
                'verbose_name_plural': 'No Docentes',
            },
        ),
        migrations.DeleteModel(
            name='EstablecimientoEducativo',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
