# Generated by Django 3.2.9 on 2021-12-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20211203_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='nodocente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen'),
        ),
    ]
