# Generated by Django 3.2.9 on 2021-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_docente_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='materia',
            field=models.CharField(choices=[('0', 'Programación 2'), ('1', 'Práctica 1'), ('2', 'Matemática Aplicada'), ('3', 'Modelado de Sistemas'), ('4', 'Sistemas Operativos'), ('5', 'Base de Datos')], default=True, max_length=50, verbose_name='Materia'),
            preserve_default=False,
        ),
    ]
